# Generated by Django 5.1.1 on 2024-09-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_no', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('nombre_huesped', models.CharField(max_length=100)),
                ('apellidos_huesped', models.CharField(max_length=100)),
                ('numero_identidad', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('motivo_viaje', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('medio_pago', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(help_text='Duración en días')),
            ],
        ),
    ]
