# Generated by Django 5.1.1 on 2024-09-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratohospedaje',
            name='reserva_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
